### ISSUE TITLE
BUG when using seriesMerge, likely due to missing data

### ISSUE THREAD

**Issue by triathematician** [triathematician/covid-analytics#122]
```
java.lang.NullPointerException
	at tri.timeseries.TimeSeriesCalcKt.dateRange(TimeSeriesCalc.kt:44)
	at tri.timeseries.TimeSeriesCalcKt.mergeSeries(TimeSeriesCalc.kt:28)
	at tri.timeseries.TimeSeriesCalcKt.max(TimeSeriesCalc.kt:64)
	at tri.timeseries.TimeSeriesCalcKt.max$default(TimeSeriesCalc.kt:64)
	at tri.timeseries.TimeSeriesCalcKt.regroupAndMax(TimeSeriesCalc.kt:86)
	at tri.timeseries.io.TimeSeriesUrlCachingProcessor.process(TimeSeriesUrlCachingProcessor.kt:43)
	at tri.timeseries.io.TimeSeriesUrlCachingProcessor.loadRaw(TimeSeriesUrlCachingProcessor.kt:49)
	at tri.timeseries.io.TimeSeriesProcessor.reloadRawData(TimeSeriesProcessor.kt:35)
```

**Comment by triathematician** [comment]
As written, mergeSeries will always fail if there is no "firstPositiveDate".

Instead, use the following:
```kotlin

/** Reduces time series by given operation, using the given reduce operation. */
fun List<TimeSeries>.mergeSeries(op: (List<Double>) -> Double): TimeSeries {
    val dates = dateRangeOrNull()
    val intSeries = all { it.intSeries }
    val values = dates?.map { date -> op(map { it[date] }) } ?: listOf()
    return get(0).copy(start = dates?.start ?: LocalDate.now(), values = values, intSeries = intSeries)
}
```
